### ISSUE TITLE
Minor improvements to the navbar

### ISSUE THREAD

**Issue by panntod** [naufalnrsmitter20/lansicare-health#46]
halo, aplikasi yang kalian buat sangat luar biasa ⭐🤩 

sedikit masukan untuk user experience yang lebih baik, yaitu untuk membedakan navbar active dan tidak aktive, sebagai contoh ketika saya berada di homepage, maka seharusnya navbar home akan berbeda dari navbar yang lain (active), kalian bisa menggunakan useLocation untuk menyeleksi sedang berada di page mana user saat ini

Happy Hacking🤖

**Comment by naufalnrsmitter20** [comment]
siap mas terimakasih banyak atas komentarnya, Insyaa Allah akan kami revisi lagi navbarnya : D

> halo, aplikasi yang kalian buat sangat luar biasa ⭐🤩
> 
> sedikit masukan untuk user experience yang lebih baik, yaitu untuk membedakan navbar active dan tidak aktive, sebagai contoh ketika saya berada di homepage, maka seharusnya navbar home akan berbeda dari navbar yang lain (active), kalian bisa menggunakan useLocation untuk menyeleksi sedang berada di page mana user saat ini
> 
> Happy Hacking🤖
